<template>

     <v-speed-dial
      location="bottom center"
      transition="slide-y-transition"
     >
      <template v-slot:activator="{ props: activatorProps }">
        <v-btn
          id="menuBouton"
          v-bind="activatorProps"
        >
          <v-badge
            :class="notConnected ? 'ping': ''"
            color="error"
            v-if="notConnected"
          >
            <img src="../../icon/icon.png" />
          </v-badge>
            
          <img src="../../icon/icon.png" v-else/>
        </v-btn>
      </template>

      <v-btn
        size="large"
        icon=""
        key="1"
        @click="openDialogMQTT(1)"
      >
        <v-badge
          color="error"
          :class="notConnected ? 'ping': ''"
          :model-value="notConnected"
        >
          <v-icon>mdi-access-point</v-icon>
        </v-badge>
      </v-btn>

      <v-btn
        size="large"
        icon="mdi-robot"
        key="2"
        :disabled="notConnected"
        @click="openDialogMQTT(2)"
      ></v-btn>

      <v-btn
        size="large"
        icon="mdi-rotate-orbit"
        key="3"
        :disabled="notConnected || store.endDevices.selectedDevices.length == 0"
        @click="openDialogMQTT(3)"
      ></v-btn>

      <v-btn
        size="large"
        :icon="store.isFullscreen ? 'mdi-fullscreen-exit' : 'mdi-fullscreen'"
        key="4"
        @click="askFullscreen"
      ></v-btn>

      <v-btn
        size="large"
        icon="mdi-cog"
        key="5"
        @click="openSettings = true"
      ></v-btn>

      <v-btn
        size="large"
        icon="mdi-github"
        key="6"
        target="_blank"
        href="https://github.com/Raserber/Suivi-de-posture"
      ></v-btn>
  </v-speed-dial>

  <Settings
    :is-visible="openSettings"
    @afterLeave="openSettings=false"
  ></Settings>
</template>
  
<script>
  import { generalStore } from '../../store';
  import Settings from './settings.vue';

  export default {
    name: "parametres",

    data: () => ({

        affichageMenu: false,
        openSettings: false
    }),

    setup() {

        const store = generalStore();

        return { store };
    },

    methods: {

      openDialogMQTT: function (step) {

        window.electronAPI.returnHostAndTopicMQTT({

            host: this.store.hostMQTT,
            topic: this.store.generalTopicMQTT
        });

        this.store.dialogBrokerMQTT.visible = true
        this.store.dialogBrokerMQTT.step = step
      },

      askFullscreen: function () {

          window.electronAPI.returnAskFullscreen(!this.store.isFullscreen)
          this.store.isFullscreen = !this.store.isFullscreen
      }
    },

    computed: {

        notConnected: ({ store }) => (store.statutMQTT != 'connect')
    },

    components: { Settings }
}
</script>

<style lang="scss">

#menuBouton {

  position: absolute;

  width: 85px;
  height: 50px;

  left: 0;

  margin-top: 8px;
  margin-left: 12px;

	background: rgba(100, 100, 100, 0.1);

	border: solid 1px rgba(0, 0, 0, 0.05);
	border-radius: 1em;
	box-shadow: inset 0 0 0.1em rgba(0, 0, 0, 0.1);

	backdrop-filter: blur(0.3em);
  

  img {

    position: relative;
    left: 50%;

    translate: -50%;
    
    height: 40px;
  }
}

  .ping {
    .v-badge__badge {
	    -webkit-animation: ping 4s ease-in-out infinite forwards;
	    animation: ping 4s ease-in-out infinite forwards;
    }
  }


  /* ----------------------------------------------
 * Generated by Animista on 2024-10-2 21:32:32
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info. 
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

/**
 * ----------------------------------------
 * animation ping
 * ----------------------------------------
 */
@-webkit-keyframes ping {
  
  0% {
    -webkit-transform: scale(0.2);
    transform: scale(0.2);
    opacity: 0.8;
  }
  
  16% {
    -webkit-transform: scale(1.2);
    transform: scale(1.2);
    opacity: 0;
  }

  20% {
    -webkit-transform: scale(2.2);
    transform: scale(2.2);
    opacity: 0;
  }
  
  21% {
    opacity: 0;
  }
  

  100% {
    opacity: 0;
  }
}
@keyframes ping {
  
  0% {
    -webkit-transform: scale(0.2);
    transform: scale(0.2);
    opacity: 0.8;
  }
  
  16% {
    -webkit-transform: scale(1.2);
    transform: scale(1.2);
    opacity: 0;
  }

  20% {
    -webkit-transform: scale(2.2);
    transform: scale(2.2);
    opacity: 0;
  }
  
  21% {
    opacity: 0;
  }
  

  100% {
    opacity: 0;
  }
}

</style>