<template>
    <v-card
        location="top right"
        position="absolute"
        width="300"
        prepend-icon="mdi-motion-outline"
        title="informations"
    >
        <v-card-text>
            <v-row cols="12">
                
                <v-col>
                    <v-divider></v-divider>
                </v-col>

                <v-col cols="12">
                    <v-chip v-bind="chipsProps" :class="isDebout ? 'bg-light-green-darken-2' : 'bg-green-lighten-5'">
                        Debout
                    </v-chip>
                </v-col>

                <v-col cols="12">
                    <v-chip v-bind="chipsProps" :class="isAssis ? 'bg-light-green-darken-2' : 'bg-green-lighten-5'">
                        Assis
                    </v-chip>
                </v-col>

                <v-col cols="12">
                    <v-chip v-bind="chipsProps" :class="isAllonge ? 'bg-light-green-darken-2' : 'bg-green-lighten-5'">
                        Allongé
                    </v-chip>
                </v-col>
                
                <v-col cols="12">
                    <v-divider></v-divider>
                </v-col>

                <v-col cols="12">
                    <v-chip
                        v-bind="timerProps"
                        :color="alarm ? 'red-lighten-1' : 'brown-lighten-4'"
                        :class="alarm ? 'jello-horizontal' : ''"
                        :prepend-icon="timer == 0 ? 'mdi-timer-pause' : ''"
                        :append-icon="alarm ? 'mdi-timer-alert' : timer != 0 ? 'mdi-timelapse' : ''"
                    >
                        {{ timer }}s
                    </v-chip>
                </v-col>
            </v-row>
            
        </v-card-text>
    </v-card>
</template>

<script>
    import { generalStore } from '../store';

    export default {

        name: "informations",

        mounted: function () {

            setInterval(()=>{

                if ((this.isAllonge || (this.store.declenchementPosAssise && this.isAssis)) && !this.store.dialogBrokerMQTT.visible) {

                    this.timer++
                }
            }, 1000)
        },
        
        data: () => ({

            timer: 0,

            chipsProps: {

                size: "x-large",
                density: "comfortable",
                variant: "outlined",
                style: "width:80%; justify-content:center;"
            },

            timerProps: {

                size: "x-large",
                density: "comfortable",
                variant: "flat",
                style: "width:120px ;height:80px ;justify-content:center;",
                rounded: "lg",
                border: "md"
            }
        }),

        watch: {
            etat: function (nValue, oldValue) {
                    if (!(nValue == "assis" && oldValue == "allonge") && !(nValue == "allonge" && oldValue == "assis")) {

                        this.timer = 0
                    }
            }
        },

        computed: {

            alarm: ({store, timer}) => (timer >= store.timerPosition),

            etat: function () {

                if (Math.abs(this.store.endDevices.angleCuisses) <= 50) {
                    return "debout"
                }

                else if (Math.abs(this.store.endDevices.angleTorse) <= 45 && -this.store.endDevices.angleCuisses >= 45) {
                    return "assis"
                }

                else {
                    return "allonge"
                }
            },

            isDebout: ({etat}) => (etat == "debout"),

            isAssis: ({etat}) => (etat == "assis"),

            isAllonge: ({etat}) => (etat == "allonge")
        },

        setup() {
            const store = generalStore()

            return { store }
        }
    }
</script>

<style scoped>

.v-card {
    margin:25px;

    background: rgba(0, 0, 0, 0.02);

    border: solid 1px rgba(0, 0, 0, 0.05);
    border-radius: 1em;
    box-shadow: inset 0 0 0.1em rgba(0, 0, 0, 0.1);

    backdrop-filter: blur(0.3em);
}
            
.v-col {
    text-align: center;
}

/*
Generated by
waitanimate.wstone.uk
*/

.jello-horizontal {
  animation: jello-horizontal 2.9s linear infinite;
  transform-origin: 50% 50%;
}

@keyframes jello-horizontal {
  0% {
    -webkit-transform: scale3d(1,1,1);
    transform: scale3d(1,1,1);
  }
  9.31% {
    -webkit-transform: scale3d(1.25,0.75,1);
    transform: scale3d(1.25,0.75,1);
  }
  12.414% {
    -webkit-transform: scale3d(0.75,1.25,1);
    transform: scale3d(0.75,1.25,1);
  }
  15.517% {
    -webkit-transform: scale3d(1.15,0.85,1);
    transform: scale3d(1.15,0.85,1);
  }
  20.172% {
    -webkit-transform: scale3d(0.95,1.05,1);
    transform: scale3d(0.95,1.05,1);
  }
  23.276% {
    -webkit-transform: scale3d(1.05,0.95,1);
    transform: scale3d(1.05,0.95,1);
  }
  31.034% {
    -webkit-transform: scale3d(1,1,1);
    transform: scale3d(1,1,1);
  }
  100% {
    -webkit-transform: scale3d(1,1,1);
    transform: scale3d(1,1,1);
  }
}
</style>