<template>

     <v-speed-dial
      location="bottom center"
      transition="fade-transition"
     >
      <template v-slot:activator="{ props: activatorProps }">
        <v-btn
          id="menuBouton"
          v-bind="activatorProps"
        >
        <v-badge
          :tag="store.statutMQTT != 'connect' ? 'parametresBouton': ''"
          color="error"
          :model-value="store.statutMQTT != 'connect'"
        >
          <img src="../icon/icon.png" />
        </v-badge>
      </v-btn>
    </template>

    <v-tooltip text="Connexion MQTT" key="1">
      <template v-slot:activator="{ props }">
        <v-badge
          color="error"
          dot
          :model-value="store.statutMQTT != 'connect'"
        >
          <v-btn
            size="large"
            v-bind="props"
            icon="mdi-connection"
            @click="store.dialogBrokerMQTT.visible = true;store.dialogBrokerMQTT.step = 1"
          ></v-btn>
        </v-badge>
      </template>
    </v-tooltip>

    <v-tooltip text="Choix End Devices" key="2">
      <template v-slot:activator="{ props }">
        <v-btn
          size="large"
          v-bind="props"
          icon="mdi-robot"
          :disabled="store.statutMQTT != 'connect'"
          @click="store.dialogBrokerMQTT.visible = true;store.dialogBrokerMQTT.step = 2"
        ></v-btn>
      </template>
    </v-tooltip>

    <v-tooltip text="Paramètres" key="3">
      <template v-slot:activator="{ props }">
        <v-btn
          size="large"
          v-bind="props"
          icon="mdi-cog"
        ></v-btn>
      </template>
    </v-tooltip>
  </v-speed-dial>
</template>
  
<script>
  import { generalStore } from '../store';

  export default {

    name: "parametres",
    
    data: () => ({

      affichageMenu : false
    }),
    
    setup() {
      const store = generalStore()
      
      return {
        store
      }
    }
  }
</script>

<style lang="scss">
#menuBouton {

  position: absolute;

  width: 85px;
  height: 50px;

  left: 0;

  margin-top: 8px;
  margin-left: 12px;

  border-radius: 1em;
  border: solid 1px rgba(0, 0, 0, 0.2);
  box-shadow: inset 0 0 1em rgba(0, 0, 0, 0.1);
  

  img {

    position: relative;
    left: 50%;

    translate: -50%;
    
    height: 40px;
  }
}

  parametresBouton {
    .v-badge__badge {
	    -webkit-animation: ping 4s ease-in-out infinite forwards;
	    animation: ping 4s ease-in-out infinite forwards;
    }
  }


  /* ----------------------------------------------
 * Generated by Animista on 2024-10-2 21:32:32
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info. 
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

/**
 * ----------------------------------------
 * animation ping
 * ----------------------------------------
 */
@-webkit-keyframes ping {
  
  0% {
    opacity: 0;
  }

  79% {
    opacity: 0;
  }

  80% {
    -webkit-transform: scale(0.2);
            transform: scale(0.2);
    opacity: 0.8;
  }
  96% {
    -webkit-transform: scale(1.2);
            transform: scale(1.2);
    opacity: 0;
  }
  100% {
    -webkit-transform: scale(2.2);
            transform: scale(2.2);
    opacity: 0;
  }
}
@keyframes ping {
  
  0% {
    opacity: 0;
  }
  
  79% {
    opacity: 0;
  }

  80% {
    -webkit-transform: scale(0.2);
            transform: scale(0.2);
    opacity: 0.8;
  }
  96% {
    -webkit-transform: scale(1.2);
            transform: scale(1.2);
    opacity: 0;
  }
  100% {
    -webkit-transform: scale(2.2);
            transform: scale(2.2);
    opacity: 0;
  }
}

</style>